id: P009228
initial_creation_type: ocr
source_metadata:
  id: bdr:W20166
  title: མཁྱེན་བརྩེའས་གུཨིདེ་ཏོ་ཐེ་ཧོལཡ་པླཅེས་ཨོཕ༹་ཅེནཏྲལ་ཏིབེཏ
  author: ''
  volumes:
    7da6c292694f4928aec4d0f5a529f4b3:
      image_group_id: I1KG16756
      title: ''
      volume_number: 1
      total_pages: 284
